services:
  grav:
      
    build: . 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      # werkt nog niet door php.ini etc
      # - GRAV_ENVIRONMENT=production
      # - S6_KEEP_ENV=1
    volumes:
      - data:/config/www/user/data
      - accounts:/config/www/user/accounts
    restart: unless-stopped
    stop_grace_period: 0s

    labels:
      - traefik.enable=true
      
      #https
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.rule=${TRAEFIK_RULE}
      # - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls=true
      # - traefik.http.routers.${COMPOSE_PROJECT_NAME}-https.tls.certresolver=letsencrypt

    networks:
      - proxynet
      - default



  smtp:
    image: mwader/postfix-relay
    environment: 
      - POSTFIX_myhostname=${POSTFIX_HOSTNAME}

    restart: unless-stopped
    stop_grace_period: 0s

networks:
  proxynet:
    name: proxynet


volumes:
  data:
    driver: ${VOL_DRIVER:-local}
  accounts:
    driver: ${VOL_DRIVER:-local}
